"""phalanx.rego — OPA/Rego policy generation from learned rules.

Converts compile_rules() output into machine-enforceable OPA policy.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def rules_to_rego(
    rules: list[dict[str, Any]],
    package_name: str = "phalanx.safety",
) -> str:
    """Convert compiled rules into a valid Rego policy string.

    Args:
        rules: List of rule dicts from compile_rules(), each with at least
               a "pattern" key.
        package_name: The Rego package declaration (dot-separated).

    Returns:
        A valid Rego policy string ready to load into OPA.
    """
    timestamp = datetime.now(tz=timezone.utc).isoformat()
    count = len(rules)

    header_lines = [
        f"package {package_name}",
        "",
        "import future.keywords.if",
        "import future.keywords.in",
        "",
        "# Auto-generated by phalanx compile — do not edit manually",
        f"# Generated: {timestamp}",
        f"# Rules: {count}",
        "",
        "default allow := false",
        "",
        "allow if {",
        "    not deny",
        "}",
        "",
    ]

    if not rules:
        # Minimal allow-all: no deny_patterns, deny rule never fires.
        deny_lines = [
            "deny if {",
            "    some pattern in deny_patterns",
            "    contains(lower(input.text), pattern)",
            "}",
            "",
            "deny_patterns := set()",
        ]
    else:
        deny_lines = [
            "deny if {",
            "    some pattern in deny_patterns",
            "    contains(lower(input.text), pattern)",
            "}",
            "",
            "deny_patterns := {",
        ]
        for rule in rules:
            # Escape any double-quotes inside the pattern
            escaped = rule["pattern"].replace('"', '\\"')
            deny_lines.append(f'    "{escaped}",')
        deny_lines.append("}")

    return "\n".join(header_lines + deny_lines) + "\n"


def export_rego(
    rules: list[dict[str, Any]],
    output_path: Path | str,
) -> Path:
    """Write the Rego policy for the given rules to output_path.

    Args:
        rules: List of rule dicts from compile_rules().
        output_path: Destination file path (created if it does not exist).

    Returns:
        The resolved output path.
    """
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(rules_to_rego(rules))
    return path
